package protocol

import (
	"crypto/rsa"
	"github.com/beaverden/smart-cards/ecommerce-protocol/internal/pkg/ecrypto/hybrid-encryption"
	"github.com/beaverden/smart-cards/ecommerce-protocol/internal/pkg/ecrypto/signature"
)

type SID int

type MerchantData struct {
	Name           string
	MerchantPubKey *rsa.PublicKey
}

type WebSegment struct {
	MerchantInfo MerchantData
	Signature    *signature.RSASignature
}

type MerchantSid struct {
	Sid          SID
	SidSignature *signature.RSASignature
}

type PaymentInfo struct {
	CardN   string         // Card number
	CardExp string         // Card expiry
	CCode   string         // Challenge Code
	Sid     SID            // Session ID
	Amount  float64        // Transfer Amount
	PubKC   *rsa.PublicKey // Client's public key
	NC      []byte         // Fresh Nonce generated by the Client
	M       string         // Merchant Identity
}

type PaymentInfoSignedFields struct {
	Sid    int           // Session ID
	PubKC  rsa.PublicKey // Client's public key
	Amount float64       // Transfer Amount
}

type PaymentMessage struct {
	Info             PaymentInfo
	DigitalSignature *signature.RSASignature // Signature over PaymentInfoSignedFields
}

type PaymentMessageToMerchant struct {
	EncryptedPM *hybrid_encryption.HybridEncryption // PM
	PO          PaymentOrder
}

type PaymentOrderSignedFields struct {
	OrderDesc string
	Sid       SID
	Amount    float64
}

type PaymentOrder struct {
	PaymentOrder     PaymentOrderSignedFields
	DigitalSignature *signature.RSASignature // Signature over PaymentOrderSignedFields
}

type PaymentMessageToPG struct {
	EncryptedPM *hybrid_encryption.HybridEncryption // PM
	MInfo       struct {
		Sid    SID
		PubKC  *rsa.PublicKey
		PubKM  *rsa.PublicKey
		Amount float64
	}
	DigitalSignature *signature.RSASignature
}

type CustomerPayment struct {
	Info  PaymentInfo
	Order PaymentOrder
}

type PaymentGatewayResponseSignedFields struct {
	Resp   string
	Sid    SID     // Session id
	Amount float64 // Payment Amount
	NC     []byte  // Client nonce
}

type PaymentGatewayResponse struct {
	Resp             string                  // YES/ABORT payment gateway message
	Sid              SID                     // Session id
	DigitalSignature *signature.RSASignature // Signature over PaymentGatewayResponseSignedFields

}
