package protocol

import (
	"crypto/rsa"
	"github.com/beaverden/smart-cards/ecommerce-protocol/internal/ecrypto/signature"
)

type MerchantData struct {
	Name           string
	MerchantPubKey *rsa.PublicKey
}

type WebSegment struct {
	MerchantInfo MerchantData
	Signature    *signature.DSASignature
}

type PaymentInfo struct {
	CardN   string        // Card number
	CardExp string        // Card expiry
	CCode   string        // Challenge Code
	Sid     int           // Session ID
	Amount  float64       // Transfer Amount
	PubKC   rsa.PublicKey // Client's public key
	NC      []byte        // Fresh Nonce generated by the Client
	M       string        // Merchant Identity
}

type PaymentInfoSignedFields struct {
	Sid    int           // Session ID
	PubKC  rsa.PublicKey // Client's public key
	Amount float64       // Transfer Amount
}

type PaymentMessage struct {
	Info             PaymentInfo
	DigitalSignature signature.DSASignature // Signature over PaymentInfoSignedFields
}

type PaymentOrderSignedFields struct {
	OrderDesc string
	Sid       int
	Amount    float64
}

type PaymentOrder struct {
	PaymentOrder     PaymentOrderSignedFields
	DigitalSignature signature.DSASignature // Signature over PaymentOrderSignedFields
}

type PaymentGatewayResponseSignedFields struct {
	Resp   string
	Sid    int     // Session id
	Amount float64 // Payment Amount
	NC     []byte  // Client nonce
}

type PaymentGatewayResponse struct {
	Resp             string                 // YES/ABORT payment gateway message
	Sid              int                    // Session id
	DigitalSignature signature.DSASignature // Signature over PaymentGatewayResponseSignedFields

}
